[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# SPA fallback so client routes work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy our frontend call to the Netlify Function in prod
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
